### ISSUE TITLE
Google fonts not supported in Internet Explorer

### ISSUE THREAD

**Issue by tracygardner** [RaspberryPiFoundation/webdev-curriculum#95]
[Mystery Letter](https://codeclubprojects.org/en-GB/webdev/mystery-letter/) project uses Google Fonts.

Google fonts gives a browser not supported error in Internet Explorer. (Edge is supported.) Unlikely that there will be a fix for this. 

Options:
- Leave as-is and mention in volunteer notes
- Remove this part of the project (it's at the end and isn't the core content)
- Try and find an alternative with cross-browser support

**Comment by martinpeck** [comment]
How is this "not supported" error seen? 
Which version of IE are you using?

I'm using IE 11.713, and don't see any issues. That might be because I've missed what you mean.

**Comment by tracygardner** [comment]
Reported by a Code Club and I'm seeing the same error on my kids Windows 10 machine which claims to be running the latest version of Explorer.

When visiting jumpto.cc/web-fonts / https://fonts.google.com 

See:
https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Ffonts.google.com

![image](https://cloud.githubusercontent.com/assets/14887827/24258682/66e7f3e8-0fe6-11e7-9183-dcad41599ac7.png)

It used to work at some point.

**Comment by martinpeck** [comment]
So, yeah...Google's fonts site has changed and no longer supports IE11 (Edge is fine).

Either way, the Google Fonts site has changed significantly. I suggest the instruction need re-writing to match the new site as the screenshots and instructions no longer match the new site.

**Comment by rtyley** [comment]
> Either way, the Google Fonts site has changed significantly. I suggest the instruction need re-writing to match the new site as the screenshots and instructions no longer match the new site.

@martinpeck  I've addressed this with https://github.com/RaspberryPiFoundation/webdev-curriculum/pull/110, with new screenshots and instructions.

**Comment by rik-cross** [comment]
@rtyley has updated the instructions, which has now been merged. Thanks @rtyley !
